export const CHANGE_TRAVEL_TYPE = 'CHANGE_TRAVEL_TYPE';
export const CHANGE_TRAVEL_DATE = 'CHANGE_TRAVEL_DATE';
export const CHANGE_TRAVEL_FROM = 'CHANGE_TRAVEL_FROM';
export const CHANGE_TRAVEL_TO = 'CHANGE_TRAVEL_TO';