export const CHANGE_TRAVEL_TYPE = 'CHANGE_TRAVEL_TYPE';
export const CHANGE_TRAVEL_DATE = 'CHANGE_TRAVEL_DATE';
export const INCREASE_PASSANGER = 'INCREASE_PASSANGER';
export const DECREASE_PASSANGER = 'DECREASE_PASSANGER';