export const CHANGE_TRAVEL_TYPE = 'CHANGE_TRAVEL_TYPE';
export const CHANGE_TRAVEL_DATE = 'CHANGE_TRAVEL_DATE';
export const CHANGE_TRAVELER_TYPE_COUNT = 'CHANGE_TRAVELER_TYPE_COUNT';
export const CHANGE_CABIN = 'CHANGE_CABIN';
export const CHANGE_TRAVEL_FROM = 'CHANGE_TRAVEL_FROM';
export const CHANGE_TRAVEL_TO = 'CHANGE_TRAVEL_TO';
export const SEARCH_AIRPORT_SUCCESS = 'SEARCH_AIRPORT_SUCCESS';
export const EXCHANGE_DESTINATIONS = 'EXCHANGE_DESTINATIONS';
export const SEARCH_AVAILABLE_FLIGHTS_SUCCESS = 'SEARCH_AVAILABLE_FLIGHTS_SUCCESS';
export const CLEAN_TRAVEL_FROM = 'CLEAN_TRAVEL_FROM';
export const CLEAN_TRAVEL_TO = 'CLEAN_TRAVEL_TO';

