const SET_CABIN = 'SET_CABIN';
const ADD_PASSENGER = 'ADD_PASSENGER';
const REMOVE_PASSENGER = 'REMOVE_PASSENGER';
const SET_TRIP = 'SET_TRIP';

export {SET_CABIN, ADD_PASSENGER, REMOVE_PASSENGER, SET_TRIP};
