const SET_CABIN = 'SET_CABIN';
const ADD_PASSENGER = 'ADD_PASSENGER';
const REMOVE_PASSENGER = 'REMOVE_PASSENGER';
const SET_TRIP_TYPE = 'SET_TRIP_TYPE';
const SET_DATE_FIRST_FLIGHT = 'SET_DATE_FIRST_FLIGHT'
const SET_DATE_SECOND_FLIGHT = 'SET_DATE_SECOND_FLIGHT'

export {SET_CABIN, ADD_PASSENGER, REMOVE_PASSENGER, SET_TRIP_TYPE, SET_DATE_FIRST_FLIGHT, SET_DATE_SECOND_FLIGHT};
